import type { YieldMarket } from "@/types/market";

// Sample markets (mock data mode). Kept in their own module so UI that only needs the
// fixtures — e.g. the landing page — does not pull in the whole adapter.
export const MOCK_MARKETS: YieldMarket[] = [
  {
    id: "usdg-morpho-26mar27",
    symbol: "USDG",
    name: "Paxos USDG",
    description:
      "Yield-bearing USDG in Morpho Prime lending vault on Robinhood Chain.",
    underlyingAsset: "USDG",
    quoteAsset: "USDG",
    yieldSource: "Morpho lending vault",
    sourceProtocol: "Morpho",
    assetMetadata: { symbol: "USDG", name: "Paxos USDG" },
    protocolMetadata: { name: "Morpho" },
    underlyingApy: 7.1,
    impliedApy: 6.42,
    maturity: "26 Mar 2027",
    maturityDate: "2027-03-26",
    daysRemaining: 175,
    liquidityUsd: 4_200_000,
    status: "active",
    network: "testnet",
    chainId: 46630,
    dataMode: "mock",
  },
  {
    id: "susde-ethena-24jun27",
    symbol: "sUSDe",
    name: "Staked USDe",
    description:
      "Synthetic dollar yield from delta-neutral basis trading on Ethena.",
    underlyingAsset: "sUSDe",
    quoteAsset: "USDG",
    yieldSource: "Ethena staking",
    sourceProtocol: "Ethena",
    assetMetadata: { symbol: "sUSDe", name: "Staked USDe" },
    protocolMetadata: { name: "Ethena" },
    underlyingApy: 9.85,
    impliedApy: 8.9,
    maturity: "24 Jun 2027",
    maturityDate: "2027-06-24",
    daysRemaining: 265,
    liquidityUsd: 2_700_000,
    status: "active",
    network: "testnet",
    chainId: 46630,
    dataMode: "mock",
  },
  {
    id: "snet-netnet-17dec26",
    symbol: "sNET",
    name: "Staked NET",
    description: "Native gas token staking yield on NetNet validator pool.",
    underlyingAsset: "sNET",
    quoteAsset: "NET",
    yieldSource: "NetNet staking",
    sourceProtocol: "NetNet",
    assetMetadata: { symbol: "sNET", name: "Staked NET" },
    protocolMetadata: { name: "NetNet" },
    underlyingApy: 5.4,
    impliedApy: 5.95,
    maturity: "17 Dec 2026",
    maturityDate: "2026-12-17",
    daysRemaining: 76,
    liquidityUsd: 900_000,
    status: "maturing",
    network: "testnet",
    chainId: 46630,
    dataMode: "mock",
  },
  {
    id: "wsteth-lido-30sep27",
    symbol: "wstETH",
    name: "Wrapped Staked ETH",
    description:
      "Liquid staking yield from Ethereum proof-of-stake consensus rewards.",
    underlyingAsset: "wstETH",
    quoteAsset: "ETH",
    yieldSource: "Lido staking",
    sourceProtocol: "Lido",
    assetMetadata: { symbol: "wstETH", name: "Wrapped Staked ETH" },
    protocolMetadata: { name: "Lido" },
    underlyingApy: 3.45,
    impliedApy: 3.2,
    maturity: "30 Sep 2027",
    maturityDate: "2027-09-30",
    daysRemaining: 363,
    liquidityUsd: 6_100_000,
    status: "active",
    network: "testnet",
    chainId: 46630,
    dataMode: "mock",
  },
];
