import { formatApy, formatUsd } from "@/lib/utils/formatters";
import type { YieldMarket } from "@/types/market";
import type { FixedYieldQuote, LongYieldQuote } from "@/types/quote";
import { marketHref } from "./featuredMarket";

/** One of the two ways to own the yield, shown as a card in the first stage. */
export interface StagePath {
  kind: "fixed" | "long";
  title: string;
  tagline: string;
  figure: string;
  caption: string;
  href: string;
}

export interface StageInfo {
  index: number;
  tag: string;
  title: string;
  accent: string;
  description: string;
  /** When present the stage shows these cards instead of the detail tabs. */
  paths?: StagePath[];
  subTabs: string[];
  subDetails: string[];
  stats: { label: string; value: string; color?: string }[];
  primaryCtaText: string;
  primaryCtaHref: string;
  secondaryCtaText: string;
  secondaryCtaHref: string;
}

export const FALLBACK_STAGES: StageInfo[] = [
  {
    index: 0,
    tag: "00 / THE PRINCIPLE",
    title: "Yield, split in two.",
    accent: "Fixed or Long\u00A0— you choose.", // nbsp keeps the dash on the previous line
    description:
      "One yield-bearing asset, two ways to earn from it: lock a fixed rate you can count on, or bet on yield rising. No liquidations, ever.",
    paths: [
      { kind: "fixed", title: "Fixed Yield", tagline: "Know exactly what you'll get.", figure: "Locked", caption: "rate until maturity", href: "/markets" },
      { kind: "long", title: "Long Yield", tagline: "Earn more if yield rises.", figure: "Variable", caption: "can also fall — value can drop", href: "/markets" },
    ],
    subTabs: ["01 Overview", "02 Dual Paths", "03 USDG Anchor"],
    subDetails: [
      "Cleave tokenizes yield into two liquid components: Principal Tokens (PT) and Yield Tokens (YT).",
      "Fixed Yield secures predictable yield upfront. Long Yield amplifies variable rate exposure.",
      "Backed 1:1 by Paxos USDG deposited in Morpho Prime lending vaults on Robinhood Chain.",
    ],
    stats: [
      { label: "UNDERLYING", value: "Paxos USDG" },
      { label: "IMPLIED APY", value: "6.42%", color: "#3B86FF" },
      { label: "SETTLEMENT", value: "Zero Liquidation" },
    ],
    primaryCtaText: "Explore markets",
    primaryCtaHref: "/markets",
    secondaryCtaText: "How the split works",
    secondaryCtaHref: "#how",
  },
  {
    index: 1,
    tag: "01 / FIXED YIELD (PT)",
    title: "Hold Certainty.",
    accent: "Zero Liquidation.",
    description:
      "Lock 6.42% fixed APY on your USDG until 26 Mar 2027. Your return is paid upfront at a discount with no margin calls, no maintenance, and zero liquidation risk.",
    subTabs: ["01 Guaranteed APY", "02 Upfront Discount", "03 Zero Liquidation"],
    subDetails: [
      "Purchase Principal Tokens (PT) at an upfront discount and redeem 1 USDG per PT at maturity.",
      "Your effective return is locked from the moment of purchase, regardless of future lending rate drops.",
      "No health ratios or liquidation liquidators. Ideal for treasury reserves and risk-averse yield seekers.",
    ],
    stats: [
      { label: "FIXED APY", value: "6.42%", color: "#3B86FF" },
      { label: "PT PRICE", value: "$0.941" },
      { label: "MATURITY", value: "26 Mar 2027" },
    ],
    primaryCtaText: "Lock Fixed Rate (PT)",
    primaryCtaHref: "/markets",
    secondaryCtaText: "View Fixed Markets",
    secondaryCtaHref: "/markets",
  },
  {
    index: 2,
    tag: "02 / LONG YIELD (YT)",
    title: "Float with the Rate.",
    accent: "10x Yield Exposure.",
    description:
      "Speculate on rising lending demand. When Morpho Prime borrower demand spikes, your Yield Tokens capture all underlying interest with amplified capital efficiency.",
    subTabs: ["01 Variable APY", "02 Yield Multiplier", "03 Rate Surges"],
    subDetails: [
      "Yield Tokens (YT) stream all interest generated by the underlying USDG vault until maturity.",
      "Because YT trades at a fraction of USDG cost (~$0.059), you gain up to 16.9x leverage on rate movements.",
      "Accumulate real-time streaming yield claimable anytime with single-transaction settlement.",
    ],
    stats: [
      { label: "VARIABLE APY", value: "7.10%", color: "#EF5F22" },
      { label: "YT PRICE", value: "$0.059" },
      { label: "EFFECTIVE LEV", value: "~16.9x", color: "#EF5F22" },
    ],
    primaryCtaText: "Trade Long Yield (YT)",
    primaryCtaHref: "/markets",
    secondaryCtaText: "View Long Markets",
    secondaryCtaHref: "/markets",
  },
  {
    index: 3,
    tag: "03 / ZERO-SUM INVARIANT",
    title: "The Split Engine.",
    accent: "Cryptographic Math.",
    description:
      "Every 1 USDG deposited mints exactly 1 Principal Token (PT) and 1 Yield Token (YT). At maturity, 1 PT redeems exactly 1 underlying USDG with zero residual risk.",
    subTabs: ["01 Tokenization", "02 Constant Sum", "03 Full Redemption"],
    subDetails: [
      "1 USDG ≡ 1 PT + 1 YT. The total market cap of PT and YT precisely equals the vault collateral.",
      "Trading creates zero protocol debt. Yield is redistributed directly between Fixed and Long market makers.",
      "Smart contracts verified on Robinhood Chain with continuous provable solvency.",
    ],
    stats: [
      { label: "INVARIANT", value: "1 USDG = 1 PT + 1 YT" },
      { label: "PROTOCOL DEBT", value: "$0.00" },
      { label: "SOLVENCY", value: "100% On-Chain" },
    ],
    primaryCtaText: "Explore Contract Specs",
    primaryCtaHref: "/contracts",
    secondaryCtaText: "How It Works",
    secondaryCtaHref: "#how",
  },
  {
    index: 4,
    tag: "04 / LIVE MARKETS",
    title: "Paxos USDG Vault.",
    accent: "Ready for Execution.",
    description:
      "Institutional yield infrastructure live on Robinhood Chain. Select Fixed or Long yield, preview exact payout in dollars, and open positions in seconds.",
    subTabs: ["01 Morpho Prime", "02 Deep Liquidity", "03 One-Click Trade"],
    subDetails: [
      "Morpho Prime Paxos USDG pool provides reliable yield derived from prime lending markets.",
      "Automated Market Maker (AMM) pools offer continuous liquidity for instant PT and YT trading.",
      "Wallet integration with seamless testnet faucet support and transparent transaction simulator.",
    ],
    stats: [
      { label: "VAULT TVL", value: "$4.25M USDG" },
      { label: "24H VOLUME", value: "$382.4K" },
      { label: "NETWORK", value: "Robinhood Chain" },
    ],
    primaryCtaText: "Launch Trading Terminal",
    primaryCtaHref: "/markets",
    secondaryCtaText: "All Vaults",
    secondaryCtaHref: "/markets",
  },
];

/**
 * Stage content for the featured market. Every number and name comes from the normalized market and its
 * quotes (mock or live); the wording around them is the product copy. Until a market is available the
 * fallback copy above is shown, so the hero never renders empty.
 */
export function buildStages(
  m: YieldMarket | null,
  fixed: FixedYieldQuote | null,
  long: LongYieldQuote | null,
): StageInfo[] {
  if (!m) return FALLBACK_STAGES;

  const S = m.symbol;
  const name = m.assetMetadata?.name ?? m.name;
  const underlying = name.length <= 18 ? name : S;
  const source = m.protocolMetadata?.name ?? m.sourceProtocol ?? m.yieldSource;
  const fixedApy = formatApy(fixed?.quotedFixedApy ?? m.impliedApy);
  const ptPrice = fixed ? `${fixed.ptPrice.toFixed(3)} ${S}` : "—";
  const ytPrice = long && long.ytPrice > 0 ? long.ytPrice : null;
  const leverage = ytPrice ? `~${(1 / ytPrice).toFixed(1)}x` : "—";
  const network = m.network === "mainnet" ? "Robinhood Chain" : "Robinhood Testnet";
  const [s0, s1, s2, s3, s4] = FALLBACK_STAGES;

  return [
    {
      ...s0,
      description: `One ${S} position, two ways to earn from it: lock a fixed rate you can count on, or bet on yield rising. No liquidations, ever.`,
      paths: [
        {
          kind: "fixed",
          title: "Fixed Yield",
          tagline: "Know exactly what you'll get.",
          figure: fixedApy,
          caption: `locked until ${m.maturity}`,
          href: marketHref(m.id, "fixed"),
        },
        {
          kind: "long",
          title: "Long Yield",
          tagline: "Earn more if yield rises.",
          figure: formatApy(m.underlyingApy),
          caption: "today, variable — can fall too",
          href: marketHref(m.id, "long"),
        },
      ],
      subDetails: [
        s0.subDetails[0],
        s0.subDetails[1],
        `Backed 1:1 by ${name}, earning through ${m.yieldSource} on Robinhood Chain.`,
      ],
      stats: [
        { label: "UNDERLYING", value: underlying },
        { label: "LIQUIDITY", value: formatUsd(m.liquidityUsd) },
        { label: "SETTLEMENT", value: "Zero Liquidation" },
      ],
      primaryCtaHref: "/markets",
    },
    {
      ...s1,
      description: `Lock ${fixedApy} fixed APY on your ${S} until ${m.maturity}. Your return is paid upfront at a discount with no margin calls, no maintenance, and zero liquidation risk.`,
      subDetails: [`Purchase Principal Tokens (PT) at an upfront discount and redeem 1 ${S} per PT at maturity.`, s1.subDetails[1], s1.subDetails[2]],
      stats: [
        { label: "FIXED APY", value: fixedApy, color: "#3B86FF" },
        { label: "PT PRICE", value: ptPrice },
        { label: "MATURITY", value: m.maturity },
      ],
      primaryCtaHref: marketHref(m.id, "fixed"),
      secondaryCtaHref: "/markets",
    },
    {
      ...s2,
      description: `Speculate on rising lending demand. When ${S} yield rises, your Yield Tokens capture all the extra interest with amplified capital efficiency.`,
      subDetails: [
        `Yield Tokens (YT) stream all interest generated by the underlying ${S} vault until maturity.`,
        ytPrice
          ? `Because YT trades at a fraction of ${S} cost (~${ytPrice.toFixed(3)}), you gain up to ${(1 / ytPrice).toFixed(1)}x exposure to rate movements.`
          : "Because YT trades at a fraction of the underlying cost, a small amount buys exposure to a much larger yield stream.",
        s2.subDetails[2],
      ],
      stats: [
        { label: "VARIABLE APY", value: formatApy(m.underlyingApy), color: "#EF5F22" },
        { label: "YT PRICE", value: ytPrice ? `${ytPrice.toFixed(3)} ${S}` : "—" },
        { label: "EFFECTIVE LEV", value: leverage, color: "#EF5F22" },
      ],
      primaryCtaHref: marketHref(m.id, "long"),
      secondaryCtaHref: "/markets",
    },
    {
      ...s3,
      description: `Every 1 ${S} deposited mints exactly 1 Principal Token (PT) and 1 Yield Token (YT). At maturity, 1 PT redeems exactly 1 underlying ${S} with zero residual risk.`,
      subDetails: [
        `1 ${S} ≡ 1 PT + 1 YT. The total market cap of PT and YT precisely equals the vault collateral.`,
        s3.subDetails[1],
        s3.subDetails[2],
      ],
      stats: [{ ...s3.stats[0], value: `1 ${S} = 1 PT + 1 YT` }, s3.stats[1], s3.stats[2]],
    },
    {
      ...s4,
      title: `${S} Vault.`,
      description: `Yield infrastructure live on Robinhood Chain. Select Fixed or Long yield, preview exact payout, and open positions in seconds.`,
      subDetails: [
        `${source} ${S} market provides yield from ${m.yieldSource}.`,
        s4.subDetails[1],
        s4.subDetails[2],
      ],
      stats: [
        { label: "LIQUIDITY", value: formatUsd(m.liquidityUsd) },
        { label: "DAYS LEFT", value: `${m.daysRemaining}d` },
        { label: "NETWORK", value: network },
      ],
      primaryCtaHref: marketHref(m.id),
      secondaryCtaHref: "/markets",
    },
  ];
}
