"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import { HeroVisual } from "./HeroVisual";
import { Navbar } from "@/components/layout/Navbar";

interface StageInfo {
  index: number;
  tag: string;
  title: string;
  accent: string;
  description: string;
  subTabs: string[];
  subDetails: string[];
  stats: { label: string; value: string; color?: string }[];
  primaryCtaText: string;
  primaryCtaHref: string;
  secondaryCtaText: string;
  secondaryCtaHref: string;
}

const STAGES: StageInfo[] = [
  {
    index: 0,
    tag: "00 / THE PRINCIPLE",
    title: "Yield, split in two.",
    accent: "Fixed or Long — you choose.",
    description:
      "Cleave splits USDG yield into PT (fixed rate, locked upfront) and YT (variable rate, amplified exposure). Settle instantly on Robinhood Chain — no liquidations, ever.",
    subTabs: ["01 Overview", "02 Dual Paths", "03 USDG Anchor"],
    subDetails: [
      "Cleave tokenizes yield into two liquid components: Principal Tokens (PT) and Yield Tokens (YT).",
      "Fixed Yield secures predictable yield upfront. Long Yield amplifies variable rate exposure.",
      "Backed 1:1 by Paxos USDG deposited in Morpho Prime lending vaults on Robinhood Chain.",
    ],
    stats: [
      { label: "UNDERLYING", value: "Paxos USDG" },
      { label: "IMPLIED APY", value: "6.42%", color: "#A9C8EE" },
      { label: "SETTLEMENT", value: "Zero Liquidation" },
    ],
    primaryCtaText: "Explore markets",
    primaryCtaHref: "/markets",
    secondaryCtaText: "How the split works",
    secondaryCtaHref: "#how",
  },
  {
    index: 1,
    tag: "01 / FIXED YIELD (PT)",
    title: "Hold Certainty.",
    accent: "Zero Liquidation.",
    description:
      "Lock 6.42% fixed APY on your USDG until 26 Mar 2027. Your return is paid upfront at a discount with no margin calls, no maintenance, and zero liquidation risk.",
    subTabs: [
      "01 Guaranteed APY",
      "02 Upfront Discount",
      "03 Zero Liquidation",
    ],
    subDetails: [
      "Purchase Principal Tokens (PT) at an upfront discount and redeem 1 USDG per PT at maturity.",
      "Your effective return is locked from the moment of purchase, regardless of future lending rate drops.",
      "No health ratios or liquidation liquidators. Ideal for treasury reserves and risk-averse yield seekers.",
    ],
    stats: [
      { label: "FIXED APY", value: "6.42%", color: "#A9C8EE" },
      { label: "PT PRICE", value: "$0.941" },
      { label: "MATURITY", value: "26 Mar 2027" },
    ],
    primaryCtaText: "Lock Fixed Rate (PT)",
    primaryCtaHref: "/trade?market=usdg-morpho-26mar27&side=fixed",
    secondaryCtaText: "View Fixed Markets",
    secondaryCtaHref: "/markets",
  },
  {
    index: 2,
    tag: "02 / LONG YIELD (YT)",
    title: "Float with the Rate.",
    accent: "10x Yield Exposure.",
    description:
      "Speculate on rising lending demand. When Morpho Prime borrower demand spikes, your Yield Tokens capture all underlying interest with amplified capital efficiency.",
    subTabs: ["01 Variable APY", "02 Yield Multiplier", "03 Rate Surges"],
    subDetails: [
      "Yield Tokens (YT) stream all interest generated by the underlying USDG vault until maturity.",
      "Because YT trades at a fraction of USDG cost (~$0.059), you gain up to 16.9x leverage on rate movements.",
      "Accumulate real-time streaming yield claimable anytime with single-transaction settlement.",
    ],
    stats: [
      { label: "VARIABLE APY", value: "7.10%", color: "#F0A85C" },
      { label: "YT PRICE", value: "$0.059" },
      { label: "EFFECTIVE LEV", value: "~16.9x", color: "#F0A85C" },
    ],
    primaryCtaText: "Trade Long Yield (YT)",
    primaryCtaHref: "/trade?market=usdg-morpho-26mar27&side=long",
    secondaryCtaText: "View Long Markets",
    secondaryCtaHref: "/markets",
  },
  {
    index: 3,
    tag: "03 / ZERO-SUM INVARIANT",
    title: "The Split Engine.",
    accent: "Cryptographic Math.",
    description:
      "Every 1 USDG deposited mints exactly 1 Principal Token (PT) and 1 Yield Token (YT). At maturity, 1 PT redeems exactly 1 underlying USDG with zero residual risk.",
    subTabs: ["01 Tokenization", "02 Constant Sum", "03 Full Redemption"],
    subDetails: [
      "1 USDG ≡ 1 PT + 1 YT. The total market cap of PT and YT precisely equals the vault collateral.",
      "Trading creates zero protocol debt. Yield is redistributed directly between Fixed and Long market makers.",
      "Smart contracts verified on Robinhood Chain with continuous provable solvency.",
    ],
    stats: [
      { label: "INVARIANT", value: "1 USDG = 1 PT + 1 YT" },
      { label: "PROTOCOL DEBT", value: "$0.00" },
      { label: "SOLVENCY", value: "100% On-Chain" },
    ],
    primaryCtaText: "Explore Contract Specs",
    primaryCtaHref: "/markets",
    secondaryCtaText: "How It Works",
    secondaryCtaHref: "#how",
  },
  {
    index: 4,
    tag: "04 / LIVE MARKETS",
    title: "Paxos USDG Vault.",
    accent: "Ready for Execution.",
    description:
      "Institutional yield infrastructure live on Robinhood Chain. Select Fixed or Long yield, preview exact payout in dollars, and open positions in seconds.",
    subTabs: ["01 Morpho Prime", "02 Deep Liquidity", "03 One-Click Trade"],
    subDetails: [
      "Morpho Prime Paxos USDG pool provides reliable yield derived from prime lending markets.",
      "Automated Market Maker (AMM) pools offer continuous liquidity for instant PT and YT trading.",
      "Wallet integration with seamless testnet faucet support and transparent transaction simulator.",
    ],
    stats: [
      { label: "VAULT TVL", value: "$4.25M USDG" },
      { label: "24H VOLUME", value: "$382.4K" },
      { label: "NETWORK", value: "Robinhood Chain" },
    ],
    primaryCtaText: "Launch Trading Terminal",
    primaryCtaHref: "/trade?market=usdg-morpho-26mar27",
    secondaryCtaText: "All Vaults",
    secondaryCtaHref: "/markets",
  },
];

const STAGE_COUNT = STAGES.length; // 5
// Scroll runway per stage in vh — shorter feels snappier
const VH_PER_STAGE = 55;
const RUNWAY_VH = STAGE_COUNT * VH_PER_STAGE; // 275vh total

export function Hero() {
  const [activeStage, setActiveStage] = useState(0);
  const [activeSubTab, setActiveSubTab] = useState(0);
  const [pointer, setPointer] = useState({ x: 0, parallaxX: 0, parallaxY: 0 });
  // true = desktop (≥1024px), false = mobile/tablet
  const [isDesktop, setIsDesktop] = useState(false);

  const runwayRef = useRef<HTMLElement>(null);
  const lastStageRef = useRef(0);
  const touchStartX = useRef(0);
  const touchStartY = useRef(0);

  const stage = STAGES[activeStage];

  // ─── Detect desktop breakpoint ────────────────────────────────────────────
  useEffect(() => {
    const mq = window.matchMedia("(min-width: 1024px)");
    setIsDesktop(mq.matches);
    const handler = (e: MediaQueryListEvent) => setIsDesktop(e.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);

  // ─── Scroll-driven stage detection (desktop only) ─────────────────────────
  useEffect(() => {
    if (!isDesktop) return;

    const onScroll = () => {
      const runway = runwayRef.current;
      if (!runway) return;
      const sectionTop = runway.getBoundingClientRect().top + window.scrollY;
      const scrolled = window.scrollY - sectionTop;
      const runwayHeight = runway.offsetHeight - window.innerHeight;
      if (runwayHeight <= 0) return;

      const progress = Math.max(0, Math.min(1, scrolled / runwayHeight));
      const newStage = Math.min(
        STAGE_COUNT - 1,
        Math.floor(progress * STAGE_COUNT),
      );

      if (newStage !== lastStageRef.current) {
        lastStageRef.current = newStage;
        setActiveStage(newStage);
        setActiveSubTab(0);
      }
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [isDesktop]);

  // ─── Pin / button click → scroll to stage position (desktop) ──────────────
  const handleSelectStage = useCallback(
    (index: number) => {
      if (!isDesktop) {
        // On mobile: just update directly without blinking
        if (index === activeStage) return;
        setActiveStage(index);
        setActiveSubTab(0);
        return;
      }

      const runway = runwayRef.current;
      if (!runway) return;
      const sectionTop = runway.getBoundingClientRect().top + window.scrollY;
      const runwayHeight = runway.offsetHeight - window.innerHeight;
      const frac = index / STAGE_COUNT;
      const targetY = sectionTop + frac * runwayHeight;
      window.scrollTo({ top: targetY, behavior: "smooth" });
    },
    [activeStage, isDesktop],
  );

  // ─── Touch swipe (mobile stage change) ────────────────────────────────────
  const handleTouchStart = (e: React.TouchEvent) => {
    touchStartX.current = e.touches[0].clientX;
    touchStartY.current = e.touches[0].clientY;
  };

  const handleTouchEnd = (e: React.TouchEvent) => {
    const dx = e.changedTouches[0].clientX - touchStartX.current;
    const dy = Math.abs(e.changedTouches[0].clientY - touchStartY.current);
    // Only treat as horizontal swipe if more horizontal than vertical
    if (Math.abs(dx) > 40 && Math.abs(dx) > dy) {
      if (dx < 0 && activeStage < STAGE_COUNT - 1) {
        handleSelectStage(activeStage + 1);
      } else if (dx > 0 && activeStage > 0) {
        handleSelectStage(activeStage - 1);
      }
    }
  };

  // ─── Pointer parallax (desktop) ───────────────────────────────────────────
  const handlePointerMove = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      const rect = e.currentTarget.getBoundingClientRect();
      const nx = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      const ny = ((e.clientY - rect.top) / rect.height) * 2 - 1;
      setPointer({
        x: nx,
        parallaxX: Math.max(-3, Math.min(3, nx * 2.5)),
        parallaxY: Math.max(-3, Math.min(3, ny * 2.5)),
      });
    },
    [],
  );

  const handlePointerLeave = useCallback(() => {
    setPointer({ x: 0, parallaxX: 0, parallaxY: 0 });
  }, []);

  const accentColor =
    activeStage === 1
      ? "#A9C8EE"
      : activeStage === 2
        ? "#F0A85C"
        : activeStage === 3
          ? "#DDE8F8"
          : activeStage === 4
            ? "#34D399"
            : "#ECEDEA";

  // ─── Shared viewport content ───────────────────────────────────────────────
  const viewportContent = (
    <div
      className="h-[100dvh] overflow-hidden flex flex-col justify-between select-none"
      onPointerMove={handlePointerMove}
      onPointerLeave={handlePointerLeave}
      onTouchStart={handleTouchStart}
      onTouchEnd={handleTouchEnd}
    >
      {/* ── DECORATIVE BACKGROUND ORBITS (Sweeping Universe Scale) ── */}
      <div
        className="absolute inset-0 pointer-events-none overflow-hidden"
        aria-hidden="true"
      >
        <svg
          viewBox="0 0 1440 940"
          className="absolute inset-0 w-full h-full"
          preserveAspectRatio="xMidYMid slice"
        >
          {/* Grand Cosmic Galactic Plane — sweeping across full width */}
          <g
            transform="translate(860 480) rotate(-22) scale(1 0.26)"
            className="orbit-slow-cw orbit-pulse"
          >
            <ellipse
              rx="1180"
              ry="1180"
              fill="none"
              stroke="rgba(169,200,238,0.07)"
              strokeWidth="1"
              strokeDasharray="16 28 6 28"
            />
            <circle cx="1180" cy="0" r="2.5" fill="#A9C8EE" opacity="0.3" />
          </g>

          {/* Deep Trans-Stellar Ellipse — opposite tilt, sweeping far wide */}
          <g
            transform="translate(820 510) rotate(16) scale(1 0.20)"
            className="orbit-slow-ccw"
          >
            <ellipse
              rx="1420"
              ry="1420"
              fill="none"
              stroke="rgba(240,168,92,0.05)"
              strokeWidth="0.85"
              strokeDasharray="8 32 4 16"
            />
            <circle cx="-1420" cy="0" r="2" fill="#F0A85C" opacity="0.35" />
          </g>

          {/* Mid-Macro Orbit — Ice Blue */}
          <g
            transform="translate(900 470) rotate(-14) scale(1 0.28)"
            className="orbit-slow-cw"
          >
            <ellipse
              rx="780"
              ry="780"
              fill="none"
              stroke="rgba(169,200,238,0.08)"
              strokeWidth="0.9"
              strokeDasharray="12 18"
            />
          </g>

          {/* Second Mid Ring — Amber harmonic */}
          <g
            transform="translate(870 490) rotate(26) scale(1 0.22)"
            className="orbit-slow-ccw"
          >
            <ellipse
              rx="620"
              ry="620"
              fill="none"
              stroke="rgba(240,168,92,0.06)"
              strokeWidth="1.1"
              strokeDasharray="6 20"
            />
          </g>

          {/* Inner celestial orbit — white tech ring */}
          <g
            transform="translate(910 460) rotate(-35) scale(1 0.24)"
            className="orbit-med-cw"
          >
            <ellipse
              rx="460"
              ry="460"
              fill="none"
              stroke="rgba(236,237,234,0.07)"
              strokeWidth="1"
              strokeDasharray="10 24"
            />
          </g>

          {/* Ultra-wide background perimeter horizon — almost horizontal, vast */}
          <g
            transform="translate(760 520) rotate(-6) scale(1 0.12)"
            className="orbit-slow-cw"
            style={{ animationDuration: "140s" }}
          >
            <ellipse
              rx="1680"
              ry="1680"
              fill="none"
              stroke="rgba(169,200,238,0.04)"
              strokeWidth="0.75"
            />
          </g>

          {/* Celestial coordinate markers */}
          <g
            opacity="0.25"
            className="mono text-[8px] tracking-[0.25em]"
            fill="#8E929B"
          >
            <text x="80" y="260">
              SECTOR · 045° RA
            </text>
            <text x="1260" y="780">
              ORBITAL PLANE · β-09
            </text>
            <line
              x1="60"
              y1="264"
              x2="72"
              y2="264"
              stroke="#8E929B"
              strokeWidth="0.8"
            />
            <line
              x1="1240"
              y1="784"
              x2="1252"
              y2="784"
              stroke="#8E929B"
              strokeWidth="0.8"
            />
          </g>
        </svg>
      </div>

      {/* Planet visual */}
      <div className="absolute inset-0 pointer-events-auto opacity-35 sm:opacity-50 lg:opacity-100 transition-opacity duration-500">
        <HeroVisual
          pointerX={pointer.x}
          parallaxX={pointer.parallaxX}
          parallaxY={pointer.parallaxY}
          activeStage={activeStage}
          onSelectStage={handleSelectStage}
          isSplitLayout={true}
        />
      </div>

      {/* Navbar */}
      <div className="relative z-30 pointer-events-auto">
        <Navbar isLanding={true} />
      </div>

      {/* Main Content */}
      <div className="relative z-20 flex-1 max-w-[1440px] w-full mx-auto px-5 sm:px-8 lg:px-16 flex items-center pointer-events-none pt-20 pb-8 sm:py-0">
        <div className="w-full lg:max-w-[480px] xl:max-w-[520px]">
          {/* Stage Badge */}
          <div className="mono flex items-center gap-2 text-[10px] sm:text-[11px] tracking-[0.22em] uppercase text-muted mb-2.5 sm:mb-3.5">
            <span
              className="w-1.5 h-1.5 rounded-full transition-colors duration-300 shrink-0"
              style={{ backgroundColor: accentColor }}
            />
            <span className="truncate">{stage.tag}</span>
          </div>

          {/* Animated Headline */}
          <div className="transition-opacity duration-300">
            <h1 className="m-0 text-[28px] xs:text-[32px] sm:text-[44px] lg:text-[58px] leading-[1.06] font-normal tracking-[-0.035em] text-foreground drop-shadow-[0_2px_30px_rgba(3,3,4,0.95)]">
              <span>{stage.title}</span>
              <br />
              <span style={{ color: accentColor }}>{stage.accent}</span>
            </h1>

            <p className="mt-3 sm:mt-4 text-[13px] sm:text-[15px] leading-[1.6] text-muted-light font-light max-w-[460px] drop-shadow-[0_1px_16px_rgba(3,3,4,0.95)] line-clamp-3 sm:line-clamp-none">
              {stage.description}
            </p>

            {/* Sub-Tabs */}
            <div className="flex gap-1.5 sm:gap-2.5 mt-4 sm:mt-5 pointer-events-auto flex-wrap">
              {stage.subTabs.map((tab, idx) => (
                <button
                  key={tab}
                  onClick={() => setActiveSubTab(idx)}
                  className={`mono text-[10px] sm:text-[11px] tracking-[0.08em] px-2.5 sm:px-3 py-1 sm:py-1.5 border transition-all duration-200 ${
                    activeSubTab === idx
                      ? "border-foreground bg-foreground/15 text-foreground font-medium"
                      : "border-white/10 text-muted hover:border-white/25 hover:text-foreground"
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>

            <div className="mt-2.5 min-h-[36px] sm:min-h-[40px] text-[12px] sm:text-[13px] text-muted leading-relaxed max-w-[460px] drop-shadow-[0_1px_8px_rgba(3,3,4,0.9)]">
              {stage.subDetails[activeSubTab]}
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-2 sm:gap-2.5 mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-white/10 max-w-[460px]">
              {stage.stats.map((st) => (
                <div key={st.label} className="flex flex-col">
                  <span className="mono text-[8px] sm:text-[9px] tracking-[0.16em] text-muted uppercase truncate">
                    {st.label}
                  </span>
                  <span
                    className="mono text-[12px] sm:text-[15px] font-medium mt-0.5 truncate"
                    style={{ color: st.color || "#ECEDEA" }}
                  >
                    {st.value}
                  </span>
                </div>
              ))}
            </div>

            {/* CTAs */}
            <div className="flex items-center gap-2.5 sm:gap-3 flex-wrap mt-5 sm:mt-6 pointer-events-auto">
              <Link
                href={stage.primaryCtaHref}
                className="inline-flex items-center gap-2 min-h-[42px] sm:min-h-[46px] px-5 sm:px-6 bg-foreground text-background font-medium text-[13px] sm:text-[14px] hover:bg-white transition-all shadow-[0_0_30px_rgba(255,255,255,0.15)]"
              >
                {stage.primaryCtaText} <span aria-hidden="true">→</span>
              </Link>
              <a
                href={stage.secondaryCtaHref}
                className="inline-flex items-center min-h-[42px] sm:min-h-[46px] px-4 sm:px-5 border border-white/20 text-[13px] sm:text-[14px] bg-background/60 hover:border-white/40 transition-colors"
              >
                {stage.secondaryCtaText}
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Stage Timeline Bar */}
      <div className="relative z-30 border-t border-white/10 bg-background/85 backdrop-blur-md px-4 sm:px-8 lg:px-16 py-3 pointer-events-auto">
        <div className="max-w-[1440px] mx-auto flex items-center justify-between gap-2 sm:gap-4">
          <div className="hidden lg:flex items-center gap-2 text-muted mono text-[11px] tracking-[0.16em] uppercase shrink-0">
            <span className="text-foreground font-semibold">+</span>
            <span>Scroll to travel</span>
          </div>

          {/* Stage dots / tabs */}
          <div className="flex items-center gap-1 sm:gap-1.5 flex-nowrap overflow-x-auto no-scrollbar py-0.5">
            {STAGES.map((s, idx) => {
              const isActive = activeStage === idx;
              return (
                <button
                  key={s.index}
                  onClick={() => handleSelectStage(idx)}
                  className={`mono text-[10px] sm:text-[11px] tracking-[0.12em] px-2 sm:px-3 py-1 sm:py-1.5 rounded transition-all duration-200 shrink-0 flex items-center gap-1 sm:gap-1.5 ${
                    isActive
                      ? "text-foreground bg-white/10 font-medium"
                      : "text-muted hover:text-foreground hover:bg-white/5"
                  }`}
                >
                  <span
                    className={`w-1.5 h-1.5 rounded-full shrink-0 ${
                      isActive ? "bg-amber-primary" : "bg-white/20"
                    }`}
                  />
                  <span>
                    0{s.index}{" "}
                    <span className="hidden md:inline">
                      {s.index === 0
                        ? "The Split"
                        : s.index === 1
                          ? "Fixed Yield"
                          : s.index === 2
                            ? "Long Yield"
                            : s.index === 3
                              ? "Split Engine"
                              : "Live Vaults"}
                    </span>
                  </span>
                </button>
              );
            })}
          </div>

          <div className="flex items-center gap-2 sm:gap-3 shrink-0">
            <div className="flex items-center gap-1">
              <button
                onClick={() => handleSelectStage(Math.max(0, activeStage - 1))}
                disabled={activeStage === 0}
                aria-label="Previous Stage"
                className="mono text-[11px] px-2 py-1 border border-white/15 text-muted hover:text-foreground hover:border-white/30 disabled:opacity-30 disabled:pointer-events-none transition-colors"
              >
                ←
              </button>
              <span className="mono text-[10px] text-muted tracking-widest px-1">
                0{activeStage + 1} / 05
              </span>
              <button
                onClick={() =>
                  handleSelectStage(Math.min(STAGE_COUNT - 1, activeStage + 1))
                }
                disabled={activeStage === STAGE_COUNT - 1}
                aria-label="Next Stage"
                className="mono text-[11px] px-2 py-1 border border-white/15 text-muted hover:text-foreground hover:border-white/30 disabled:opacity-30 disabled:pointer-events-none transition-colors"
              >
                →
              </button>
            </div>
            <a
              href="#how"
              onClick={(e) => {
                e.preventDefault();
                document
                  .getElementById("how")
                  ?.scrollIntoView({ behavior: "smooth" });
              }}
              className="hidden sm:inline-flex mono text-[10px] tracking-[0.14em] text-muted hover:text-foreground transition-colors border-l border-white/15 pl-2.5 sm:pl-3"
            >
              All Sections ↓
            </a>
          </div>
        </div>
      </div>
    </div>
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // DESKTOP  → sticky scroll runway (275vh)
  // MOBILE   → plain single viewport, no runway, swipe to change stage
  // ═══════════════════════════════════════════════════════════════════════════
  if (!isDesktop) {
    return (
      <section id="top" className="relative bg-background">
        {viewportContent}
      </section>
    );
  }

  return (
    <section
      id="top"
      ref={runwayRef}
      className="relative bg-background"
      style={{ minHeight: `${RUNWAY_VH}vh` }}
    >
      <div className="sticky top-0">{viewportContent}</div>
    </section>
  );
}
